gen/generator.go
gen/generator_test.go

Hi Victor! Thanks for a such good library! :+1: 
Just little fix here.
Some keys could be like `"Some_Mixed_Case"`. Before this fix `camelToSnake` was returning `some__mixed__case` instead of `some_mixed_case`.

Fix to `camelToSnake` function to handle properly `Some_Snake_Case` string

---

jwriter/writer.go

Hi! Thanks for the tool! In my case it's relay faster than ffjson)
You had a bug on escaping strings in Marshaler.
E.e. with input `<script type="text/javascript" src="http://example.com/script.js"></script>` marshaling result was `"<script type="text/javascript" src="http://example.com/script.js"></script>\"text/javascript" src="http://example.com/script.js"></script>\" src="http://example.com/script.js"></script>\"http://example.com/script.js"></script>\"></script>"` 
With fix result is `"<script type=\"text/javascript\" src=\"http://example.com/script.js\"></script>"`

Fix for escaping in Writer.String #11

---

gen/encoder.go
tests/basic_test.go
tests/data.go

https://golang.org/pkg/encoding/json/#Marshal
> Struct values encode as JSON objects. Each exported struct field becomes a member of the object unless
> 
> - the field's tag is "-", or
> - the field is empty and its tag specifies the "omitempty" option.
This PR implements the "-" part.
Without it I can't use easyjson as a drop-in replacement of the standard JSON marshalling.

Ignore struct fields tagged with "-"

---

bootstrap/bootstrap.go
parser/parser_unix.go
parser/parser_windows.go

This fixes issues that were preventing builds on Windows, specifically:
- adds rough normalization of paths to work on Windows and Cygwin (backslashes!), where previously it would complain about things not being in the GOPATH
- fixes two issues where os.Rename fails because rename is attempted before the file is closed
With these fixes it seems to work fine, though I've not done exceedingly thorough testing.

Add support for Windows paths, fix file handling errors for Windows

---

jlexer/lexer.go

Incomplete incoming data caused unmarshaler panic: `slice bounds out of range`
E.g. if JSON data is:
```json
{
"somefield": "data",
"anotherfi
```
application crashes with 
```
panic: runtime error: slice bounds out of range
goroutine 1666 [running]:
panic(0xab9740, 0xc82001c040)
/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/mailru/easyjson/jlexer.(*Lexer).fetchToken(0xc820cc6cb0)
/usr/local/go/src//github.com/mailru/easyjson/jlexer/lexer.go:58 +0x3dc
github.com/mailru/easyjson/jlexer.(*Lexer).IsDelim(0xc820cc6cb0, 0x7d, 0xb95028)
/usr/local/go/src/github.com/mailru/easyjson/jlexer/lexer.go:427 +0x3a
...
```

Fixed panic in lexer.fetchToken

---

gen/encoder.go

Using a pointer for MarshalJson is unecessary.
It caused me a small surprise where I was marshalling a struct (not its pointer), and discovered via code coverage that the easyjson generated code was not called.
I've run the tests, nothing broken, and it does not seem to change benchmark results (I get some small variances between runs so it's hard to compare, but the results stay in the same range).

Do not use a pointer for MarshalJson

---

easyjson/main.go

The generated bootstrapping code requires gen; exposing this
otherwise-indirect dependency makes life easier for people wishing to
vendor easyjson so that they will pull in all the necessary
dependencies.

Reference the gen package from easyjson

---

Makefile
gen/decoder.go
gen/encoder.go
tests/data.go
tests/required.go
tests/required_test.go

I`ve done very straight forward implementation for required keys as we discussed in #24
So for struct
```go
type Person struct {
Firstname string `json:"first_name,required"`
Lastname  string `json:"last_name"`
}
```
this code will be generated:
```go
func easyjson_4f3adcb_decode_github_com_mailru_easyjson_tests_RequiredOptionalStruct(in *jlexer.Lexer, out *RequiredOptionalStruct) {
if in.IsNull() {
in.Skip()
return
}
var first_nameSet bool
in.Delim('{')
for !in.IsDelim('}') {
key := in.UnsafeString()
in.WantColon()
if in.IsNull() {
in.Skip()
in.WantComma()
continue
}
switch key {
case "first_name":
out.FirstName = string(in.String())
first_nameSet = true
case "last_name":
out.Lastname = string(in.String())
default:
in.SkipRecursive()
}
in.WantComma()
}
in.Delim('}')
if !first_nameSet { …
```

required keys support

---

.gitignore
jlexer/error.go
jlexer/lexer.go

- Creates LexerError type for all possible parse errors generated by the
Lexer, except for standard JSON library errors or through AddError
method;
- Updates .gitignore to exclude JetBrain family directories and files.
The `Lexer` type simply returns errors using `fmt.Errorf`, while this is fine and functional, it's often challenging for library users to know what the error really is unless we sniff into the string. Having a typed error improves the usage of the library. Consider the following snippet:
```go
func SomeBigFunc(input []byte) error {
if input == "some special case" {
return &SomeSpecificError{}
}
err := easyjson.Unmarshal(input, someGoodVar)
if err != nil {
// I would like to handler the error, but I don't have enough information to handle it here, so I send it up.
return err …
```

Creates LexerError type

---

bootstrap/bootstrap.go

I missed this in #15.
Today it caused one of my generation to fail with error:
```
cannot use someVar (type someType) as type easyjson.Marshaler in argument to easyjson.MarshalToWriter:
someType does not implement easyjson.Marshaler (MarshalEasyJSON method has pointer receiver)
```

Remove pointer-receivers for Marshalling funcs in bootstrap file

---

Makefile
bootstrap/bootstrap.go
gen/generator.go
tests/nothing.go

If the file doesn't contain any structs for generator, generated file becomes invalid, because it contains imports which are not used (jlexer and jwriter are always imported). It makes difficult to use easyjson for batch generation on directory which may contain some files without structs (or without //easyjson:json comment).

Fix generating valid files with no types to marshal/unmarshal in file

---

gen/decoder.go
gen/generator.go
tests/data.go

There is a bug with named types after #39 merge. Named types are replaced by underlying type so generated code has error with types.
See test cases for more details.

Fix generated code for named types

---

gen/decoder.go

From https://golang.org/pkg/encoding/json/#Unmarshal:
To unmarshal JSON into a pointer, Unmarshal first handles the case of the JSON being the JSON literal null. In that case, Unmarshal sets the pointer to nil. Otherwise, Unmarshal unmarshals the JSON into the value pointed at by the pointer. If the pointer is nil, Unmarshal allocates a new value for it to point to.

Follow standard encoding/json unmarshalling logic for pointers

---

jlexer/lexer.go
jlexer/lexer_test.go

Fixing EOF error to appear while having double slashes at the end of the string. 
This bug resulted in an error while trying to Unmarshal an object that has some attributes with custom UnmarshalJSON method.

SkipRecursive fails while having double slashes at the end of the string

---

gen/encoder.go

Now interface fields in struct marshal via json.Marshal, it's very slow in case of this field implements easyjson marshaler and can marshal via MarshalJSON(). So we can just check if it field json.Marshaler and use MarshalJSON() instead of json.Marshal, and we get the best performance.

Use MarshalJSON() instead of json.Marshal() for interface type if it implements json.Marshaler

---

gen/decoder.go
gen/encoder.go
gen/generator.go
tests/basic_test.go
tests/data.go

Arrays are useful to decode into to keep the allocations down
and thus the gc pressure low.
The code allows the json to contain truncated arrays without
raising an error, same as standard encoding/json. However excess
elements in the json is an error.

Add support for array types

---

gen/generator.go
gen/generator_test.go

According to https://github.com/golang/go/issues/12739
and to https://github.com/mailru/easyjson/issues/29

Remove vendor path from imports. PkgPath() workaround.

---

gen/decoder.go
jlexer/lexer.go
jlexer/lexer_test.go

Resolves https://github.com/mailru/easyjson/issues/72
Shouldn't have any significant real-world performance impact, since most JSON that gets passed around does not have trailing bytes. This just catches things that _aren't_ valid JSON 😉

Assert that no extraneous data remains after top-level tokens

---

Makefile
gen/encoder.go
gen/generator.go
tests/basic_test.go
tests/nested_easy.go

Suppose we have the following struct:
```
type Struct struct {
A int
B string
C interface{}
}
```
The code generated for the C field is something like:
```
if m, ok := C.(json.Marshaler); ok {
out.Raw(m.MarshalJSON())
} else {
out.Raw(json.Marshal(C))
}
```
Even if we generate std marshalers it will be slow. So let's add another cast to easyjson.Marshaler interface and use it for marshalling if supported. 
```
if m, ok := C.(easyjson.Marshaler); ok {
m.MarshalEasyJSON(out)        
} else if m, ok := C.(json.Marshaler); ok {
out.Raw(m.MarshalJSON())
} else {
out.Raw(json.Marshal(C))
}
```

Allow interface{} fields to be marshaled using easyjson.Marshaler

---

jwriter/writer.go

This option is similar to [json.Encoder.SetEscapeHTML](https://golang.org/pkg/encoding/json/#Encoder.SetEscapeHTML). The default behavior of false is to escape &, <, and > to \u0026, \u003c, and \u003e. Setting this to true will not escape these characters.

Add NoEscapeHTML to jwriter.Writer

---

jlexer/lexer.go
jlexer/lexer_test.go

fixes issue #79

---

gen/decoder.go
gen/generator.go
tests/basic_test.go
tests/data.go

This pull request fixes a bug connected with unmarshaling struct which contains interface field, where interface is a pointer to another struct. Instead of filled embedded struct we get `map[string]interface{}`. See `TestUnmarshalStructWithEmbeddedPtrStruct` for example.

Fix unmarshaling struct with interface field which is a pointer to another struct

---

Makefile
gen/generator.go
tests/basic_test.go
tests/named_type.go

Named types inside anonymous structs aren't getting the proper package prefix. For example field S in
package P
type T2 <something>
type T struct {
S struct {
F T2
}
}
gets converted by the generator.go into
struct { 
F P.T2
}
Note the "P." prefix. It's wrong. We are already in package P.
This pull request fixes this and similar cases.
----------------------
The fix is to not use the output of reflect.Type.String(). reflect.Type.String() almost returns the right thing, but not quite. It qualifies all named types with their package. That breaks 2 ways:
1) when the type's package == g.pkgPath
2) when the type's package name clashes with a package alias easyjson picked
The fix is to enumerate the anonymous struct's fields ourself, converting each field's type ourself.

fix bugs in generator output for named types inside anonymous structs

---

buffer/pool.go
jwriter/writer.go

This adds an optional parameter to `BuildBytes()` which allows for reusing
of a byte buffer. Because it's an optional parameter it will not break
backwards compatibility.
This allows people to use a `sync.Pool` for the buffers used by
`BuildBytes()` to reduce garbage generation.

Allow reusing of buffer in BuildBytes()

---

jlexer/lexer.go

Do not run lexer.Consumed if there's an error.

---

bootstrap/bootstrap.go
gen/generator.go

Fixed ordering in bootstrap and generator when there are multiple types in a single file. Fixes an issue where multiple/repeated runs were not generating the same output, which was frustrating when run across a large project with thousands of types.

Changing to fixed ordering for generator when multiple types in single file

---

buffer/pool.go
buffer/pool_test.go
jwriter/writer.go

When marshalling something as body for a `http.Request` we can only use
`BuildBytes()` which always allocates a buffer for our whole body. This
pull request adds a `ReadCloser()` method which returns an `io.ReadCloser`
that can be passed as body into `http.NewRequest`. This `ReadCloser` will
read from the existing buffs and `putBuf` them when they are not needed
anymore.

Add ReadCloser method to jwriter and buffer

---

buffer/pool.go

See: https://github.com/golang/go/issues/19186
When the body isn't fully read and Close is called multiple times we put the same buffer in the pool multiple times causing it to be reused by multiple goroutines at the same time.

Prevent bugs caused by multiple Close calls

---

README.md
benchmark/data_codec.go
jlexer/bytestostr.go
jlexer/bytestostr_nounsafe.go
jlexer/lexer.go

Package `unsafe` is used in jlexer to prevent copying when casting from []byte to string, speeding up the marshalling process to a large extent. However, `unsafe` is not allowed in environments such as Google Appengine.
Therefore two build tags are introduced, which either of them can disable the use of unsafe package, falling back to conventional copy-based []byte to string conversion. The build tags are `easyjson_nounsafe` and `appengine` (which is set when building for Google Appengine)
This commit solves issue https://github.com/mailru/easyjson/issues/34

Introduce build tags to disable unsafe package usage

---

gen/decoder.go
gen/encoder.go
jlexer/lexer.go
jwriter/writer.go
tests/basic_test.go
tests/data.go

Currently easyjson doesn't handle [encoding.TextMarshaler][1] interfaces. This leads to a situation where types like [net.IP][2] are handled as Base64Bytes:
```go
ip := net.IPv4(192, 168, 0, 1)
s, _ := easyjson.Marshal(ip)
// "AAAAAAAAAAAAAP//wKgAAQ=="
s, _ := json.Marshal(ip)
// "192.168.0.1"
```
[1]: https://godoc.org/encoding#TextMarshaler
[2]: https://godoc.org/net#IP

Proper encoding.TextMarshaler handling

---

gen/generator.go

I have "-" characted in some of my imports, and generated file has bad syntax in import section, which causing "Bootstrap failed" error. Fixed by replacing "-" character with empty character in aliases names.

Replace dash with empty character in import alias name

---

gen/generator.go

I have my private package with some structures I depend on, stored by path like `.../my-private-structs.git`. In this case nothing works... This patch fix it.

package path with "." bug fix

---

parser/parser.go
parser/parser_test.go
parser/parser_unix.go
parser/parser_windows.go

os.Getwd() on Windows sometimes returns an upper case drive letter and sometimes a lower case drive letter. It changes depending on if the program is run as a binary or from a "go run .." command line.
Anyway, this results in GOPATH not being equal to the working directory unless GOPATH is using an upper case drive letter. getPkgPath then returns "file '%v' is not in GOPATH"
Switching to filepath means you can probably eliminate the _unix and _windows files completely, but I didn't want to change the code too much so I left the normalizePath() function in there. I also wrote some a test as well. You'll probably want to move that to your test directory if you decide to keep it.

Updated getPkgPath to use package filepath instead of path

---

jlexer/lexer.go

I have the following json string
```
{"request":{"stringField":"foo"}}
```
I get the following message when i try to parse it :
```
"parse error: invalid character '}' after top-level value near offset 13 of '}'"
```
I expected the message : 
```
"parse error: "boolField" is required"
```
This is my go struct
```
type BarRequest struct {
StringField string `json:"stringField,required"`
BoolField   bool   `json:"boolField,required"`
}
type Bar_Normal_Args struct {
Request *BarRequest `json:"request,required"`
}
```
The checking for extra bytes on the end of the json top level object check overwrites the useful message with a cryptic undebuggable message.

Update lexer.Consumed() to not overwrite existing error

---

gen/decoder.go

This function can return an error which we currently ignore. Be explicit
about this. Primarily this is so linters will not complain (specifically [errcheck](https://github.com/kisielk/errcheck)) when run against a package with generated code.

Explicitly ignore error from UnmarshalJSON()

---

README.md
bootstrap/bootstrap.go
easyjson/main.go
gen/generator.go
gen/generator_test.go

Adds the `--lower-camel-case` option to name fields in `lowerCamelCase` instead of `UpperCamelCase`.
Obviously you can't do this normally in the structs as fields starting with a lowercase letter are private and cannot be seen.

Add lowerCamelCase naming strategy

---

gen/generator.go

I put it in when adding the feature in my last PR but didn't end up using it, so removing it in this PR

Get rid of unused isNumeric() function

---

easyjson/main.go

This commit trims whitespace around the build tags specified on the
command line in order that invocations such as:
```
easyjson -build_tags linux
```
generate the correct:
```
// +build linux
```
rather than adding additional whitespace, giving
```
// +build  linux
```

Trim whitespace around build tags

---

gen/generator.go

Say the import pkg is `pkg/v1`, and one var name may be `v1` too. The conflict will fail the build.
In the fix we add `_` before the alias name if it starts with character
`v`.

Avoid pkg alias naming conflict with vars

---

.travis.yml
Makefile
benchmark/jsoniter_test.go

I wanted to check how easyjson works, compared to [json-iterator/go](https://github.com/json-iterator/go) aka jsoniter, which looks like an attractive replacement for a standard `encoding/json`.
According to jsoniter's own [benchmarks](https://github.com/json-iterator/go-benchmark), it performs on the same level with easyjson, while doesn't require code generation.
Below are the results of running benchmarks on my MacBook Pro 2016 (2 GHz Intel Core i5) with Go 1.9.
```
% go test -benchmem -tags use_easyjson -bench . github.com/mailru/easyjson/benchmark
goos: darwin
goarch: amd64
pkg: github.com/mailru/easyjson/benchmark
BenchmarkEJ_Unmarshal_M-4                   	   30000	     49584 ns/op	 262.66 MB/s	    9792 B/op	     128 allocs/op
BenchmarkEJ_Unmarshal_S-4                   	 2000000 …
```

Add jsoniter to benchmarks

---

gen/decoder.go
gen/encoder.go
tests/non_string_keyed_map_test.go

When seeing an unsupported type (e.g., `map[int]string`), easyjson behaves correctly and exits with status code 1. However, if the unsupported type is nested (e.g., `map[string]map[int]string`), easyjson exits with status code 0 and generates invalid code silently, as mentioned in https://github.com/mailru/easyjson/issues/50. Below is an example:
```go
➜  easyjson git:(master) ✗ cat foo.go
package easyjson
//easyjson:json
type Foo map[string]map[int]string
➜  easyjson git:(master) ✗ ./.root/bin/easyjson foo.go && echo 'success'
success
➜  easyjson git:(master) ✗ cat foo_easyjson.go
...
func easyjsonE4de407aEncodeGithubComMailruEasyjson(out *jwriter.Writer, in Foo) {
if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
out.RawString(`null`)
} else {
out.RawByte('{')
v2First := true
for …
```

[Bug Fix] Handle errors when generating encoder/decoder for nested structures

---

gen/decoder.go
jlexer/lexer.go
jlexer/lexer_test.go

Both go native encoding/json json.Unmarshal and ffjson's UnmarshalJSON methods could unmarshal following json-encoded strings:
* `{"number": 10}`
* `{"number": "20"}`
to 
```
.... struct {
Number json.Number `json:"number"`
}
```
But easyjson got error on unmarshaling second json-encoded string.

Feature: allow to unmarshal json.Number

---

parser/parser.go
parser/parser_unix.go
parser/parser_windows.go

It is no longer required to have the GOPATH environment variable set - it now defaults to ~/go, but irrespective of whether the value is the default or not it can be found in the standard output of `go env GOPATH`.
This commit uses that value if the GOPATH environment variable is not set.

Detect GOPATH if not specified in $GOPATH

---

benchmark/data.go
tests/data.go

Проблема возникала из-за того, что при передаче в fmt.Sprint() целочисленной константы с явно не указанным типом math.MaxUint32 рефлект, сидящий где-то глубоко в Sprint, определял тип константы как int (точнее говоря при присвоении пустому интерефейсу константы её тип указывался как int). При этом сама константа в в int могла и не помещаться, что и происходило в 32-bit системах.

fix problem with installation on 32-bit system 

---

opt/gotemplate_Bool.go
opt/gotemplate_Float32.go
opt/gotemplate_Float64.go
opt/gotemplate_Int.go
opt/gotemplate_Int16.go
opt/gotemplate_Int32.go
opt/gotemplate_Int64.go
opt/gotemplate_Int8.go
opt/gotemplate_String.go
opt/gotemplate_Uint.go
opt/gotemplate_Uint16.go
opt/gotemplate_Uint32.go
opt/gotemplate_Uint64.go
opt/gotemplate_Uint8.go
opt/optional/opt.go
tests/opt_test.go

There were two problems with the optional type wrapper implementation that this PR fixes.
1) `UnmarshalJSON` didn't actually use the provided `data` parameter, always leading to EOF errors. Mentioned in #152.
2) `MarshalJSON` was a pointer method. Thus only `*opt.String` satisfied the `json.Marshaler` interface and `opt.String` didn't, so `json.Marshal` output `{"V":"foo","Defined":true}` instead of `"foo"`.
I also added a test to make sure this stays operational.

Fix optional type wrapper's standard marshaler.

---

Makefile
gen/generator.go
tests/basic_test.go
tests/embedded_type.go

I found a bug in some code I sent last year which handles unnamed types. The bug is that embedded types inside unnamed types weren't generating code which would compile.
This fixes it, as well as adds a unit test for this sort of situation.

Embedded unnamed types fix

---

Makefile
gen/decoder.go
gen/encoder.go
tests/basic_test.go
tests/custom_map_key_type.go

The stdlib json supports maps whose keys have custom MarshalJSON and UnmarshalJSON methods.
This adds support for this case to easyjson, as well as a unit test of such a situation.

Custom marshaler map key type support

---

gen/decoder.go
gen/encoder.go
jlexer/lexer.go
jwriter/writer.go
tests/data.go

When a float would have a `json: ",string"` – the parser would fail if it got some json that had a float "string" type
Signed-off-by: Levi Gross <levi@levigross.com>

Add float string functions when requested

---

gen/decoder.go
gen/encoder.go
tests/basic_test.go
tests/data.go

The generator works wrong if we have a pointer on an array.
Sample code:
```go
type IntArray [2]int
//easyjson:json
type IntArrayStruct struct {
Pointer *IntArray `json:"pointer"`
Value   IntArray  `json:"value"`
}
```
The error:
```
.root/src/github.com/mailru/easyjson/tests/data_easyjson.go:3838: invalid indirect of out.Pointer[v71] (type int)
.root/src/github.com/mailru/easyjson/tests/data_easyjson.go:3895: invalid indirect of in.Pointer[v73] (type int)
```
The generated code is before the fix:
```go
for !in.IsDelim(']') {
if v71 < 2 {
*out.Pointer[v71] = int(in.Int()) // <------------
v71++
} else {
in.SkipRecursive()
}
in.WantComma()
}
```	
After the fix:
```go
for !in.IsDelim(']') {
if v71 < 2 {
(*out.Pointer)[v71] = int(in.Int()) // <------------
v71++
} else {
in.SkipRecursive()
} …
```

fix invalid indirect of a pointer on a array

---

jlexer/lexer.go

I noticed this while integrating master with #163 into my project. The issue is that the position did not get updated correctly causing it to reprocess the token. I looked for examples that test the position in `lexer_test.go` but did not see any.

Correctly consume the null value for json.Number

---

parser/parser.go
parser/parser_windows.go

fix #162 for win and handle last newline character from `go env GOPATH`, sorry that I'm not included this in previous pull request

#162 using default GOPATH for win and trim last newline character

---

parser/parser_windows.go

If there is a package with an import path that is not all lowercase, then easyjson will fail.
```
package main: case-insensitive import collision: "github.com/xStrom/skoll/src/api" and "github.com/xstrom/skoll/src/api"
```
This bug was introduced with PR #130.
The code contains a comment which claims that "*Windows file systems will almost always be case insensitive*". This is a common misconception and not true. [NTFS is case sensetive](https://support.microsoft.com/en-us/help/100625/filenames-are-case-sensitive-on-ntfs-volumes). Although yes most Win32 applications are case insensetive, which is where the confusion comes from. Still, the filesystem itself is case sensetive and it's perfectly legal to write applications that utilize this.
Looking deeper we find issue #129. There it is …

Fix handling of non-lowercase packages on Windows.

---

jlexer/lexer.go
jlexer/lexer_test.go

Fixes panic during processing jlexer.Data with the same length and capacity

Fix lexer.errInvalidToken panic

---

.travis.yml
gen/decoder.go
tests/embedded_type.go

See 	https://play.golang.org/p/KXZbjG0JBle for an example
```go
package main
import (
"fmt"
"encoding/json"
)
func main() {
type Embed1 struct {
Field1 int
}
type Embed2 struct {
Field2 int
}
type test struct {
Embed1
Embed2 `json:"named"`
}
var v test
data, _ := json.MarshalIndent(v, "", "\t")
fmt.Println(string(data))
}
```
```json
{
"Field1": 0,
"named": {
"Field2": 0
}
}
```

Stdlib json handles embedded structs with json tags differently.

---

bootstrap/bootstrap.go

Fixing a very little typo as a stub is created and not a number of stubs

Fix a little typo

---

.gitignore
gen/decoder.go
tests/data.go
tests/required_test.go

As reported in issue #256, currently, an empty map is unmarshalled into nil by easyjson
If a field is marked "required" or "!omitempty", then the empty map is a valid input and
we should unmarshal it into an empty map.
Similar logic for marshalling.
This change is to fix the behavior

Allow empty maps for required map fields (issue #256)

---

jwriter/writer.go

Reference the escape tables by pointer, instead of allocating 128 bytes on the stack and copying the full table for every call to Writer.String
```
name                              old time/op    new time/op    delta
EJ_Unmarshal_M-4                    33.6µs ± 1%    34.3µs ± 5%   +2.00%  (p=0.006 n=9+10)
EJ_Unmarshal_S-4                     458ns ± 2%     464ns ± 5%     ~     (p=0.397 n=10+10)
EJ_Marshal_M-4                      11.8µs ± 1%    11.4µs ± 1%   -3.25%  (p=0.000 n=10+9)
EJ_Marshal_L-4                       577µs ± 1%     535µs ± 1%   -7.30%  (p=0.000 n=9+10)
EJ_Marshal_L_ToWriter-4              508µs ±13%     446µs ± 2%  -12.38%  (p=0.000 n=10+9)
EJ_Marshal_M_Parallel-4             4.26µs ±10%    4.17µs ± 4%     ~     (p=0.226 n=9+8)
EJ_Marshal_M_ToWriter-4 …
```

Do not copy escape tables

---

buffer/pool.go
buffer/pool_test.go

Allow to inline the fast path of AppendString and AppendBytes.
Also fix a related test and some copy-pasted comments.
```
name                              old time/op    new time/op    delta
EJ_Unmarshal_M-4                    33.3µs ± 1%    33.6µs ± 3%     ~     (p=0.095 n=9+10)
EJ_Unmarshal_S-4                     462ns ± 0%     465ns ± 1%     ~     (p=0.084 n=8+9)
EJ_Marshal_M-4                      12.4µs ± 1%    10.9µs ± 2%  -12.11%  (p=0.000 n=10+9)
EJ_Marshal_L-4                       586µs ± 1%     522µs ± 1%  -10.96%  (p=0.000 n=9+10)
EJ_Marshal_L_ToWriter-4              505µs ± 3%     428µs ± 5%  -15.31%  (p=0.000 n=10+9)
EJ_Marshal_M_Parallel-4             3.75µs ± 1%    3.32µs ± 2%  -11.45%  (p=0.000 n=10+10)
EJ_Marshal_M_ToWriter-4             11.0µs ± 2%     9.6µs ± 4% …
```

Make Buffer.Append{String,Bytes} inlineable

---

buffer/pool.go

Split the slow path into a separate function, so that the fast path in EnsureSpace becomes inlineable.
This allows code in jwriter to inline the fast path.
```
name                              old time/op    new time/op    delta
EJ_Unmarshal_M-4                    33.4µs ± 1%    34.3µs ± 6%  +2.93%  (p=0.002 n=8+10)
EJ_Unmarshal_S-4                     462ns ± 0%     462ns ± 1%    ~     (p=0.994 n=9+10)
EJ_Marshal_M-4                      12.4µs ± 1%    11.6µs ± 1%  -6.60%  (p=0.000 n=9+9)
EJ_Marshal_L-4                       585µs ± 1%     586µs ± 1%    ~     (p=0.739 n=10+10)
EJ_Marshal_L_ToWriter-4              507µs ± 2%     511µs ± 9%    ~     (p=1.000 n=10+10)
EJ_Marshal_M_Parallel-4             3.73µs ± 2%    3.58µs ± 3%  -4.06%  (p=0.000 n=10+10)
EJ_Marshal_M_ToWriter-4 …
```

Make Buffer.EnsureSpace inlineable

---

parser/modulepath.go
parser/pkgpath.go
parser/pkgpath_test.go
parser/testdata/comments.go.mod
parser/testdata/comments_deps.go.mod
parser/testdata/default.go.mod
parser/testdata/missing_module.go.mod

It's required because:
- go.mod file can contain comments
- easyjson should respect comments and be able to parse go.mod
This commit replaces the logic of parsing go.mod file with the original
one from golang.org/x/mod/modfile package. Tests have been
introduced to check the behavior of `getModulePath` function.
Ref:
- https://golang.org/cmd/go/#hdr-The_go_mod_file

parser: Fix go.mod endline comments parsing

---

parser/pkgpath.go

Fix case when file is located in gopath but they have different volume letter. For example:
Error parsing fast.go: file 'E:\!project\go\src\coursera\hw3_bench\fast.go' is not in GOPATH 'e:\!project\go\'
1) filepath.Rel takes care about that;
2) add gopath variable to error

Windows only issue - mismatch in volume letter

---

gen/decoder.go

Fixes issue with
```
panic: runtime error: integer divide by zero
goroutine 1 [running]:
github.com/mailru/easyjson/gen.(*Generator).genTypeDecoderNoCheck(0xc0000b2b40, 0x8a7ce0, 0x789a60, 0xc0000d3a18, 0xf, 0x775e5c, 0xb, 0x0, 0x3, 0x1, ...)
/home/user/go/pkg/mod/github.com/mailru/easyjson@v0.0.0-20190806181939-d838132d3919/gen/decoder.go:127 +0x5b9f
github.com/mailru/easyjson/gen.(*Generator).genTypeDecoder(0xc0000b2b40, 0x8a7ce0, 0x789a60, 0xc0000d3a18, 0xf, 0x775e5c, 0xb, 0x0, 0x3, 0x0, ...)
/home/user/go/pkg/mod/github.com/mailru/easyjson@v0.0.0-20190806181939-d838132d3919/gen/decoder.go:85 +0x51e
github.com/mailru/easyjson/gen.(*Generator).genStructFieldDecoder(0xc0000b2b40, 0x8a7ce0, 0x8061e0, 0x775e49, 0xb, 0x0, 0x0, 0x8a7ce0, 0x789a60, 0x775e56, ...) …
```

fix panic divide by zero

---

parser/parser.go

If a directory is passed to the command line tool, the directory
includes test files, and those test files specify types that the tool is
interested in (e.g. struct types) then it will trigger a compiler error,
fail to generate, and leave some detritus in the target directory.
We should filter out test files from consideration to prevent this error
from occuring. Future development could include a command line option to
process test files, if anyone wants that (unlikely).

Issue #217: handling of _test.go files

---

gen/decoder.go

When I use easyjson for my structs I get an error "_**cannot generate decoder for customTypes.DurationInSecond: error processing embedded field: got time.Duration; expected a struct**_".
This is a struct that causes an error.
```
type DurationInSeconds struct {
time.Duration
}
func(dis DurationInSeconds) func1() {}
func(dis DurationInSeconds) func2() {}
```
So I explore the code of generator and improved func genStructFields.
Looks like it works on my project now (generated, compiled and tested on few structs).
I would like to run tests, but I can't figure out how to run them(I'm on Windows).

improved gen getStructFields: for anonymous field that is not a struct.

---

Makefile
README.md
bootstrap/bootstrap.go
easyjson/main.go
gen/decoder.go
gen/generator.go
jlexer/lexer.go
jlexer/lexer_test.go
tests/members_escaped.go
tests/members_escaping_test.go
tests/members_unescaped.go

There are 2 issues with current implementation (addresses issue #264 ):
1. It performs a plain byte to byte loop to find string boundaries and
perform unescaping. Replace this with bytes.IndexByte() implementation.
2. It performs unescaping of string values even when this is not really
needed, e.g. for members which are absent in target data structure.
This patch fixes both issues and results in ~12% faster BenchmarkEJ_Unmarshal_M-8,
plus number of allocations goes down from 128 to 52 (!):
```
benchmark                                     old MB/s     new MB/s     speedup
BenchmarkEJ_Unmarshal_M-8                     317.99       356.27       1.12x
BenchmarkEJ_Unmarshal_S-8                     142.19       139.77       0.98x
benchmark                                     old allocs     new …
```

Optimisations: use bytes.IndexByte() + delay unescaping (#264)

---

parser/parser.go
parser/pkgpath.go

Old approach was failing for me on macOS, so I always had to run `export GOPATH=$(go env GOPATH)` before using easyjson. I did not bother debugging it -- I just rewrote it.
This approach seems to be more solid, and should work on go1.8+.

Use go/build to get default GOPATH

---

Makefile
README.md
benchmark/go.sum
gen/decoder.go
gen/encoder.go
go.mod
jlexer/lexer.go
jlexer/lexer_test.go
tests/basic_test.go
tests/intern.go
tests/intern_test.go

Uses [josharian/intern](https://github.com/josharian/intern) to optionally perform string interning during unmarshaling.
Saves one allocation per string field.
Fixes https://github.com/mailru/easyjson/issues/191

Implement optional string interning

---

gen/decoder.go
gen/encoder.go

My attempt take on #194 
Checking for interface whether or not `interface` implements (Un)marshalers (json and easyjson ones) and if so -- generating code which uses it without additional runtime check

Add checks for json/easyjson marshaler/unmarshaler interfaces

---

Makefile
README.md
gen/decoder.go
gen/encoder.go
tests/nocopy.go
tests/nocopy_test.go

When large amounts of data are unmarshaled for immediate non long live use than
copying of strings from original buffer can be avoided and instead a
reference to the original buffer returned in the field value.
Note, if the value requires unescaping, than it will be processed as
normally done with copying.
Signed-off-by: Kirill Korotaev <kirillx@gmail.com>

Add "nocopy" json tag to return unsafe string reference

---

Makefile
README.md
parser/parser.go
tests/basic_test.go
tests/type_declaration.go
tests/type_declaration_skip.go

It allows manually control which structs should be skipped when using option `-all`.
Closes #288

Added pragma easyjson:skip to exclude structs from generating stage

---

go.sum

#279 added the `intern` dependency, but didn't commit the `go.sum` file. `go.sum` should always be [tidy and committed](https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file).

Tidy and commit go.sum

---

gen/decoder.go

#202 introduced a spurious print to the code generator. It doesn't break things as-is because it appears to print before the rest of the code (so it only adds to the first line, which is already the "DO NOT EDIT" header).

Remove spurious print

---

jlexer/lexer.go
jlexer/lexer_test.go

Hey there. Very interesting project! Here a suggestion 
Since json data is not validated for skipped data when calling Unmarshal on the struct directly. This poses in my opinion a security risk
```
{"x": [ ### something unverified like an image or a link or what ever # ]}
```
json data like the one above could pass unverified in the system ...
What do you think?
BTW the benchmarks on my system don't change with this change.
Best Michael

jlexer skipped json value validation added

---

jlexer/lexer.go
jlexer/lexer_test.go

Fixed lexer in decoding base64-encoded []byte field with forward slash in it.

Unmarshalling fails if base64-encoded string contains forward slash

---

jlexer/bytestostr.go

The current implementation of `bytesToStr` uses an unsafe `reflect.StringHeader` value. Change the implementation of this function to a safe and simpler version.
To explain what could go wrong here is some example code:
```go
var d []byte
d = someFunctionThatReturnsBytes()
s := bytesToStr(d)
doSomethingWith(s)
```
When this code gets compiled `bytesToStr` would get inlined and the code would be like the following. I have included in comments at which point things could go wrong:
```go
var d []byte
d = someFunctionThatReturnsBytes()
h := (*reflect.SliceHeader)(unsafe.Pointer(&d))
shdr := reflect.StringHeader{Data: h.Data, Len: h.Len}
// At this point in time d and d.Data have nothing referencing them anymore
// shdr.Data is an uintptr so it will be ignored by the GC.
// This means d and …
```

Fix bytesToStr

---

jlexer/lexer.go
jlexer/lexer_test.go

Updated implementation of #308, the issue is still relevant and hasn't been addressed.

Make current token kind public and accessible via Lexer.CurrentToken

---

gen/encoder.go
jwriter/writer.go
tests/data.go

В данный момент, если мы попытаемся замаршалить что-то такое, без кастомных маршаллеров
```
test := example.ExampleStruct{
ExampleMap: map[example.ExampleKey]string{
"":     "val1",
"key2": "val2",
},
}
```
то получим 
`{"example_map":{"":"val1","key2":"val2"}}`
Если в тип выше добавить кастомные маршаллеры
```
func (k ExampleKey) MarshalText() ([]byte, error) {
return []byte(k), nil
}
```
То получим невалидный json
`{"example_map":{null:"val1","key2":"val2"}}`
И при попытке его обратно заанмаршалить получим ошибку:
`panic: parse error: expected string near offset 20 of 'example_map'`
Это происходит из-за использовании функции RawText
```
func (w *Writer) RawText(data []byte, err error) {
switch {
case w.Error != nil:
return
case err != nil:
w.Error = err
case len(data) > 0: …
```

Fix null key in map

---

gen/decoder.go
tests/basic_test.go

Unmarshaling null value on an existing field does not set it to nil.
The generated unmarshal code today adds this block of code that skips the field if it is null: https://github.com/mailru/easyjson/blob/853c4976cc1dc774f4653967e1ed9bae04ffbbb5/gen/decoder.go#L517-L521
This means the field is skipped and does not get set to nil.
However, there is already an `if in.IsNull()` check on the individual field that sets the field to nil as expected: https://github.com/mailru/easyjson/blob/529b1f6f7ec18fbae380d7ce72d38061e5201498/gen/decoder.go#L234-L240
So removing the first check fixes this issue.
The added test fails today because it does not overwrite the `Ptr` field to nil, which is the stdlib behavior as shown here: https://goplay.tools/snippet/8Y3_1RK1C3u
As far as I can tell, the removed …

Fix unmarshal null to existing value

---

gen/decoder.go
tests/basic_test.go

#407 fixed the issue where an explicit null field did not reset the value, but a regression was introduced where previously it skipped any null values for non-pointer fields, that now returns an error.
This PR adds a `IsNull()` check before each unmarshal and the result is the same behavior as I see with stdlib now.
eg. stdlib ignores any null values for non-pointer fields: https://goplay.tools/snippet/dEJi7819RKc
The updated unit test also validates this behavior.
Without this change, the updated test fails to unmarshal:
```
--- FAIL: TestUnmarshalNull (0.00s)
basic_test.go:341: easyjson.Unmarshal() error: parse error: expected string near offset 14 of 'String'
basic_test.go:345: Wanted "bla", got ""
basic_test.go:349: Wanted nil, got "bla"
```

Fix unmarshal null values for non-pointer fields
